### ISSUE TITLE
Websocket support is broken due to missing Header

### ISSUE THREAD

**Issue by baank** [tumblr/colossus#423]
In both current (0.8.0) and master I  am not able to connect to a WebSocket server using the HTML5 WebSocket API JS client.

As described in the implementation the client will make a HTTP request call with the "Upgrade" connection header. However /colossus/src/main/scala/colossus/protocols/http/Header.scala is unaware of this and will throw the error below.

The fix is quite simple. Just add a new Connection case object with type "upgrade" and add it to the apply sequence.

``
[ERROR] [07/01/2016 14:28:40.484] [MyApp-server-dispatcher-11] [/myapp-websocket(akka://MyApp)] Error processing request: Invalid Request: colossus.parsing.ParseException: Invalid connection header value 'Upgrade'
colossus.parsing.ParseException: Invalid connection header value 'Upgrade'
	at colossus.protocols.http.Connection$$anonfun$apply$6.apply(Header.scala:366)
	at colossus.protocols.http.Connection$$anonfun$apply$6.apply(Header.scala:366)
	at scala.Option.getOrElse(Option.scala:121)
	at colossus.protocols.http.Connection$.apply(Header.scala:366)
	at colossus.protocols.http.HttpParse$HeadersBuilder.add(HttpParse.scala:49)
	at colossus.protocols.http.HttpParse$.folder(HttpParse.scala:19)
	at colossus.protocols.http.HttpParse$$anonfun$headers$2.apply(HttpParse.scala:20)
	at colossus.protocols.http.HttpParse$$anonfun$headers$2.apply(HttpParse.scala:20)
	at colossus.parsing.Combinators$FoldZeroParser.parse(Parsing.scala:726)
	at colossus.parsing.Combinators$ChainedParser.parse(Parsing.scala:169)
	at colossus.parsing.Combinators$ChainedParser.parse(Parsing.scala:164)
	at colossus.parsing.Combinators$MapParser.parse(Parsing.scala:131)
	at colossus.parsing.Combinators$FlatMapParser.parse(Parsing.scala:144)
	at colossus.protocols.http.BaseHttpServerCodec.decode(HttpServerCodec.scala:14)
``

**Comment by baank** [comment]
Just noticed that this has already been fixedin the Pull Request. Can close.
